# Site settings
title: National Provider Directory
short_title: NPD - National Provider Directory
description: |
    A functional National Provider Directory implementation and reference architecture based on Master Data Management Principles and powered by InterSystems Healthshare and Google Cloud Platform.
baseurl: ""
url: "http://opendatahandbook.org" # the base hostname & protocol for your site
github_username:  sween
github_repo:  national_provider_directory
# paypal: admin@okfn.org
contact: https://discuss.okfn.org/c/network-and-community/open-data-handbook

devs:
  -
      name:  Ron Sweeney
      github: sween

contributors:
  -
      name: Ron Sweeney
      link: http://www.integraionrequired.com

supporters:
  -
    name: InterSystems Corporation
    logo: intersys_healthshare-logo.png
    footer_logo: intersys_healthshare-logo.png
    url: http://www.intersystems.com
  -
    name: Google Cloud Platform
    logo: google_cloud-logo.png
    footer_logo: google_cloud-logo.png
    url: https://cloud.google.com/


#googleanalytics: UA-XXXXX-X

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts


related_projects:
  -
      name: OpenGovernmentData.org
      link: http://opengovernmentdata.org/
  -
      name: The DataHub
      link: http://datahub.io/

